[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "retro-sdk"
version = "0.1.1"
description = "python sdk for retro, the photo sharing app!"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["requests"]